<a href="https://colab.research.google.com/github/Saqlain2/Data-Preprocessing-Using-PANDAS/blob/main/BOG_LOG_REG_NB_RF_ON_IMDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("C:\\Users\\SaifzWorld.Lenovo-PC\\Desktop\\saqlain_csv\\labeledTrainData.tsv",delimiter = "\t")

In [ ]:
data.tail()


id  sentiment                                             review
24995   3453_3          0  It seems like more consideration has gone into...
24996   5064_1          0  I don't believe they made this film. Completel...
24997  10905_3          0  Guy is a loser. Can't get girls, needs to buil...
24998  10194_3          0  This 30 minute documentary Buñuel made in the ...
24999   8478_8          1  I saw this movie as a child and it broke my he...

In [ ]:
np.bincount(data.sentiment)

array([12500, 12500], dtype=int64)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()


x_train,x_test,y_train,y_test=train_test_split(data.review,data.sentiment,test_size=0.3)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(17500,) (7500,) (17500,) (7500,)


In [ ]:
x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [ ]:
features_name = vectorizer.get_feature_names()
print("number of features: {}".format(len(features_name)))

number of features: 64761


In [ ]:
vectorizer.vocabulary_

{'who': 63093,
 'ever': 19669,
 'wrote': 63920,
 'the': 57427,
 'two': 59554,
 'or': 40664,
 'three': 57704,
 'glowing': 24076,
 'reviews': 48004,
 'were': 62844,
 'either': 18304,
 'involved': 29838,
 'in': 28566,
 'making': 34962,
 'of': 40261,
 'this': 57619,
 'film': 21248,
 'term': 57233,
 'used': 61040,
 'loosely': 34078,
 'bank': 5003,
 'rolling': 48660,
 'it': 30055,
 'and': 2776,
 'should': 51756,
 'latter': 32770,
 'be': 5423,
 'case': 9357,
 'would': 63792,
 'want': 62405,
 'my': 38544,
 'seven': 51065,
 'dollars': 16859,
 'back': 4652,
 'actors': 1388,
 'again': 1824,
 'are': 3522,
 'awful': 4506,
 'fact': 20366,
 'almost': 2352,
 'none': 39618,
 'them': 57460,
 'did': 15804,
 'anything': 3170,
 'which': 62984,
 'is': 29975,
 'relief': 47249,
 'scenery': 50042,
 'everything': 19695,
 'about': 1050,
 'screams': 50368,
 'we': 62641,
 'had': 25395,
 'to': 58118,
 'work': 63708,
 'with': 63473,
 'day': 14446,
 'do': 16708,
 'was': 62494,
 'filmed': 21263,
 'someones': 53296,
 '

In [ ]:
#CV AND ACCURACY

In [ ]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
scores =cross_val_score(LogisticRegression(),x_train,y_train,cv=5)
print("mean cv accuracy : {}".format(np.mean(scores)))


mean cv accuracy : 0.8728


In [ ]:
#Checking LOG REG ,NBMULTINOMIAL ,RANDOM FOREST

In [ ]:
logregression = LogisticRegression()
logregression.fit(x_train,y_train)
print("training set scores : {}".format(logregression.score(x_train,y_train)))
print("test set scores : {}".format(logregression.score(x_test,y_test)))

training set scores : 0.9881142857142857
test set scores : 0.8764


In [ ]:
from sklearn.metrics import confusion_matrix
pred_log = logregression.predict(x_test)
confusion_mat = confusion_matrix(y_test,pred_log)
print("confusion mat :\n{}".format(confusion_mat))


confusion mat :
[[3273  505]
 [ 422 3300]]


In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb =  MultinomialNB()
nb.fit(x_train,y_train)
print("training set scores : {}".format(nb.score(x_train,y_train)))
print("test set scores : {}".format(nb.score(x_test,y_test)))


training set scores : 0.9062857142857143
test set scores : 0.8524


In [ ]:
pred_log = nb.predict(x_test)
confusion_mat = confusion_matrix(y_test,pred_log)
print("confusion mat :\n{}".format(confusion_mat))


confusion mat :
[[3329  449]
 [ 658 3064]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf =  RandomForestClassifier()
rf.fit(x_train,y_train)
print("training set scores : {}".format(rf.score(x_train,y_train)))
print("test set scores : {}".format(rf.score(x_test,y_test)))


training set scores : 1.0
test set scores : 0.8468


In [ ]:
pred_log = rf.predict(x_test)
confusion_mat = confusion_matrix(y_test,pred_log)
print("confusion mat :\n{}".format(confusion_mat))


confusion mat :
[[3174  604]
 [ 545 3177]]


In [ ]:
#checking the review and classifying them

In [ ]:
review = "this movie is was bad"
print("logistic regression prediction : {}".format(logregression.predict(vectorizer.transform([review]))[0]))
print("Naive bayes prediction :\n{}" .format(nb.predict(vectorizer.transform([review]))[0]))
print("Random forest prediction : \n{}".format(rf.predict(vectorizer.transform([review]))[0]))  

logistic regression prediction : 0
Naive bayes prediction :
0
Random forest prediction : 
0


In [ ]:
review = "this movie is was not too good"
print("logistic regression prediction : {}".format(logregression.predict(vectorizer.transform([review]))[0]))
print("Naive bayes prediction :\n{}" .format(nb.predict(vectorizer.transform([review]))[0]))
print("Random forest prediction : \n{}".format(rf.predict(vectorizer.transform([review]))[0]))  

logistic regression prediction : 0
Naive bayes prediction :
0
Random forest prediction : 
1


In [ ]:
review = "this movie is was good"
print("logistic regression prediction : {}".format(logregression.predict(vectorizer.transform([review]))))
print("Naive bayes prediction :\n{}" .format(nb.predict(vectorizer.transform([review]))))
print("Random forest prediction : \n{}".format(rf.predict(vectorizer.transform([review]))))  

logistic regression prediction : [1]
Naive bayes prediction :
[0]
Random forest prediction : 
[1]


In [ ]:
review = "this movie is not that bad"
print("logistic regression prediction : {}".format(logregression.predict(vectorizer.transform([review]))))
print("Naive bayes prediction :\n{}" .format(nb.predict(vectorizer.transform([review]))))
print("Random forest prediction : \n{}".format(rf.predict(vectorizer.transform([review]))))  

logistic regression prediction : [0]
Naive bayes prediction :
[0]
Random forest prediction : 
[0]
