<a href="https://colab.research.google.com/github/Saqlain2/Data-Preprocessing-Using-PANDAS/blob/main/hyperparameter_on_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets , svm
iris = datasets.load_iris()

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(iris.data ,columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x : iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [ ]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9555555555555556

In [ ]:
from sklearn.model_selection import cross_val_score

cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)


array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [ ]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5).mean()

0.9733333333333334

In [ ]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [ ]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5).mean()

0.9800000000000001

In [ ]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [ ]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5).mean()

0.9800000000000001

In [ ]:
#same with now using GRID SEARCH CV

In [ ]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma="auto"),
                  {'C' :[ 1,10,20,] ,
                  'kernel' : ['rbf', 'linear']}
                  ,cv=5,return_train_score=False
                  )
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00219855, 0.00099978, 0.00100064, 0.00100079, 0.00100374,
        0.00046124]),
 'std_fit_time': array([3.96324534e-04, 1.41130911e-06, 3.01578299e-07, 1.90734863e-07,
        6.20254995e-06, 9.22489166e-04]),
 'mean_score_time': array([0.00080094, 0.00020127, 0.00059981, 0.00080051, 0.00080051,
        0.00081224]),
 'std_score_time': array([0.00040047, 0.00040255, 0.00079945, 0.00040026, 0.00040026,
        0.00040672]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [ ]:
df1 = pd.DataFrame(clf.cv_results_)
df1

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.002199  3.963245e-04         0.000801        0.000400       1   
1       0.001000  1.411309e-06         0.000201        0.000403       1   
2       0.001001  3.015783e-07         0.000600        0.000799      10   
3       0.001001  1.907349e-07         0.000801        0.000400      10   
4       0.001004  6.202550e-06         0.000801        0.000400      20   
5       0.000461  9.224892e-04         0.000812        0.000407      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [ ]:
df1[['param_kernel','param_C','mean_test_score']]

param_kernel param_C  mean_test_score
0          rbf       1         0.980000
1       linear       1         0.980000
2          rbf      10         0.980000
3       linear      10         0.973333
4          rbf      20         0.966667
5       linear      20         0.966667

In [ ]:
#RANDOMSEARCH CV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
clf = RandomizedSearchCV(svm.SVC(gamma="auto"),
                  {'C' :[ 1,10,20,] ,
                  'kernel' : ['rbf', 'linear']}
                  ,cv=5,return_train_score=False,n_iter=2
                  )
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00140133, 0.00180273]),
 'std_fit_time': array([0.00080054, 0.00075032]),
 'mean_score_time': array([0.00080109, 0.00060067]),
 'std_score_time': array([0.00040054, 0.00049045]),
 'param_kernel': masked_array(data=['rbf', 'rbf'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[10, 20],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 10}, {'kernel': 'rbf', 'C': 20}],
 'split0_test_score': array([0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.96666667, 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.98      , 0.96666667]),
 'std_test_score': array([0.01632993, 0.03651484]),
 'rank_test_score': array([1, 2])}

In [ ]:
df2 = pd.DataFrame(clf.cv_results_)
df2

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.001605      0.000799         0.000603        0.000493          rbf   
1       0.000999      0.000004         0.000798        0.000399          rbf   

  param_C                      params  split0_test_score  split1_test_score  \
0      10  {'kernel': 'rbf', 'C': 10}           0.966667                1.0   
1      20  {'kernel': 'rbf', 'C': 20}           0.966667                1.0   

   split2_test_score  split3_test_score  split4_test_score  mean_test_score  \
0           0.966667           0.966667                1.0         0.980000   
1           0.900000           0.966667                1.0         0.966667   

   std_test_score  rank_test_score  
0        0.016330                1  
1        0.036515                2

In [ ]:
df2[['param_kernel','param_C','mean_test_score']]

param_kernel param_C  mean_test_score
0          rbf      10         0.980000
1          rbf      20         0.966667

In [ ]:
# now calculating are best model for iris data set

In [ ]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression


In [ ]:
model_params = {
    
    "svm" : {
             "model" : svm.SVC(gamma="auto"),
             "params": {
                'C' :[ 1,10,20,] ,
                'kernel' : ['rbf', 'linear']
             }   
    },
    "random_forest" : {
             "model" : RandomForestClassifier(),
             "params": {
                 'n_estimators' : [1,5,10]
             }   
    },
    
    "log_regression" : {
             "model" : LogisticRegression(solver='liblinear',multi_class='auto'),
             "params": {
                 'C' : [1,5,10]
             }   
    }
}

In [ ]:
scores = []
for model_name,mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(iris.data,iris.target)
    
    
    scores.append({
        "model" : model_name,
        'best_scores': clf.best_score_,
        "best_params": clf.best_params_
     })

In [ ]:
scores

[{'model': 'svm',
  'best_scores': 0.9800000000000001,
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_scores': 0.96,
  'best_params': {'n_estimators': 5}},
 {'model': 'log_regression',
  'best_scores': 0.9666666666666668,
  'best_params': {'C': 5}}]

In [ ]:
df_scores = pd.DataFrame(scores,columns =['model','best_scores','best_params'])
df_scores

model  best_scores                best_params
0             svm     0.980000  {'C': 1, 'kernel': 'rbf'}
1   random_forest     0.960000        {'n_estimators': 5}
2  log_regression     0.966667                   {'C': 5}